version: "2"

services:

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.0.16
    entrypoint: ["/filebrowser", "-d", "/filebrowser-db/filebrowser.db"]
    restart: always
    volumes:
      - ${DOWNLOAD_DIR}:/srv
      - filebrowser:/filebrowser-db/
    ports:
      - 127.0.0.1:9000:80

  rtorrent:
    container_name: rtorrent
    restart: always
    build:
      context: ./alpine-rtorrent
      args:
        - UID=${RTORRENT_UID}
        - GID=${RTORRENT_GID}
    image: alpine-rtorrent:local
    networks:
      - torrent
    volumes:
      - rtorrent-session:/home/rtorrent/rtorrent/.session
      - ${DOWNLOAD_DIR}:/home/rtorrent/rtorrent/download
    ports:
      - 50000:50000
      - 6881:6881
      - 6881:6881/udp
    expose:
      - 16891

  flood:
    container_name: flood
    restart: always
    image: jesec/flood:latest
    depends_on:
      - rtorrent
    networks:
      - torrent
    volumes:
      - flood-rundir:/rundir
      - ${DOWNLOAD_DIR}:/home/rtorrent/rtorrent/download
    ports:
      - 127.0.0.1:9010:3000
    environment:
      - HOME:/rundir
      - FLOOD_OPTION_secret=${FLOOD_SECRET}
      - FLOOD_OPTION_allowpath=/home/rtorrent/rtorrent/download
      - FLOOD_OPTION_rthost=rtorrent
      - FLOOD_OPTION_rtport=16891

volumes:
  filebrowser:
  rtorrent-session:
  flood-rundir:

networks:
  torrent:
